AWSTemplateFormatVersion: 2010-09-09
Description: "Reference Price PA Data Populator"
Parameters:
  PADataStoragePrefix:
    Description: Prefix of PA input data BucketName
    Type: String
    Default: pa-data
    AllowedValues:
      - pa-data
  IntermediateStorage:
    Description: S3 bucket name to store intermediate files
    Type: String
    Default: cp-ref-price-poc-bucket
  PADatabaseJDBCUrl:
    Type: String
    Description: JDBC url of the database used to persist PA data
    Default: "jdbc:mysql://reference-db-mysql-cluster.cluster-c6xai0tt38eb.us-east-1.rds.amazonaws.com:3306/REF_PRICE_001"
  PADatabasePassword:
    Type: String
    Description: Password of the database used for glue connection
    Default: ""
    NoEcho: true
  SecurityGroupListForGlueConnction:
    Type: CommaDelimitedList
    Description: Security group list for glue connection
    Default: sg-06a4893b70fc2f68f
  SubnetIdForGlueConnection:
    Type: String
    Description: The subnetId to be referred
    Default: subnet-0ad1216eb31e15186
  AvailabilityZoneForGlueConnection:
    Type: String
    Description: The Availability Zone of the glue connection
    Default: us-east-1b
    AllowedValues:
      - us-east-1a
      - us-east-1b
      - us-east-1c
      - us-east-1d
      - us-east-1e
      - us-east-1f
  EnvironmentShort:
    Description: Environment for application
    Type: String
    Default: DEV
    AllowedValues:
      - DEV
      - QA
      - STG
      - EXE
      - TST
      - PROD
    ConstraintDescription: Must be a valid environment
  PONumber:
    Description: PO Number for billing
    Type: String
    Default: '7000002358'
    MinLength: '1'
    MaxLength: '255'
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: Must contain only ASCII characters.
  ApplicationID:
    Description: Application ID - Official Application_ID, this is generated by Sysco's
      CMDB
    Type: String
    Default: APP-001151
    MinLength: '1'
    MaxLength: '255'
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: Must contain only ASCII characters.
  ApplicationName:
    Description: Application_Name - Common, user-friendly name
    Type: String
    Default: Cloud Pricing
    MinLength: '1'
    MaxLength: '255'
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: Must contain only ASCII characters.
  Approver:
    Description: Person approving instance funding.  This should be Email address
      formatted
    Type: String
    Default: villanueva.loi@corp.sysco.com
    MinLength: '1'
    MaxLength: '255'
  Owner:
    Description: Email address usually Product/ Platform Owner, though team distribution
      list for technical product/platform team contact
    Type: String
    Default: krishan.senevirathne@sysco.com
    MinLength: '1'
    MaxLength: '255'
  Component:
    Description: Component name
    Type: String
    Default: Reference Pricing Api
  SupportEmail:
    Description: Email distribution list for technical product/platform team contact
    Type: String
    Default: 000-BT-PricingPlatform@Corp.sysco.com
    MinLength: '1'
    MaxLength: '255'
  ProjectID:
    Description: Project_ID - BT Project ID for this workload
    Type: String
    Default: BT.001176
    MinLength: '1'
    MaxLength: '255'
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: Must contain only ASCII characters.
  2WTAGGER:
    Description: Used by 2nd Watch Managed Services in shared accounts to determine
      if a resource is supported
    Type: String
    Default: team-managed
    MinLength: '1'
    MaxLength: '255'
    AllowedValues:
      - team-managed
      - adlm-managed
      - 2w-managed
    ConstraintDescription: Must contain only ASCII characters.
  Platform:
    Description: Platform
    Type: String
    Default: Cloud Pricing V4

Mappings:
  EnvMap:
    DEV:
      val: dev
    QA:
      val: qa
    STG:
      val: stg
    EXE:
      val: exe
    TST:
      val: tst
    PROD:
      val: prod

Resources:

  PAETLTriggerLambaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'PAETLTriggerLambaRole-${EnvironmentShort}'
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/PermissionBoundary-DevOps'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: StartStepFunctionExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource:
                  - '*'
      Path: '/'

  PAETLStepFunctionExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub 'PAETLStepFunctionExecutionRole-${EnvironmentShort}'
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/PermissionBoundary-DevOps'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - !Sub 'states.${AWS::Region}.amazonaws.com'
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
      Policies:
        - PolicyName: ExecuteGlueJobPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - glue:GetJobs
                  - glue:BatchStopJobRun
                  - glue:ListJobs
                  - glue:CreateJob
                  - glue:BatchGetJobs
                  - glue:StartJobRun
                  - glue:GetJobRun
                  - glue:UpdateJob
                  - glue:GetJobRuns
                  - glue:GetJob
                Resource: "*"
        - PolicyName: LogStepFunctionEventPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:DescribeDestinations
                  - logs:PutDestination
                  - logs:CreateLogDelivery
                  - logs:GetLogDelivery
                  - logs:UpdateLogDelivery
                  - logs:DeleteLogDelivery
                  - logs:ListLogDeliveries
                  - logs:PutResourcePolicy
                  - logs:DescribeResourcePolicies
                  - logs:DescribeLogGroups
                Resource: '*'
      Path: '/'

  PAETLGlueRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'PAETLGlueRole-${EnvironmentShort}'
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/PermissionBoundary-DevOps'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'glue.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
        - !Sub 'arn:aws:iam::${AWS::AccountId}:policy/CloudPricing-IAM-SSM-Policy'
      Policies:
        - PolicyName: PAETLGlueJob
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:CreateLogGroup
                  - logs:PutLogEvents
                  - logs:AssociateKmsKey
                Resource: 'arn:aws:logs:*:*:/aws-glue/*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - 'arn:aws:s3:::sysco-us-east-1-prcp-nonprod-codedeploy/ReferencePricingApi/DataPopulator/*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub 'arn:aws:s3:::${IntermediateStorage}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${IntermediateStorage}'
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub
                  - 'arn:aws:s3:::cp-ref-${PADataStoragePrefix}-storage-${env}/*'
                  - { env: !FindInMap [ EnvMap, !Ref EnvironmentShort, val ]}
      Path: '/'

  PADataStorage:
    DependsOn: LambdaInvokePermission
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub
        - 'cp-ref-${PADataStoragePrefix}-storage-${env}'
        - { env: !FindInMap [ EnvMap, !Ref EnvironmentShort, val ]}
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt PAInputTrigger.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: gz

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt PAInputTrigger.Arn
      Principal: s3.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !Sub
        - 'arn:aws:s3:::cp-ref-${PADataStoragePrefix}-storage-${env}'
        - { env: !FindInMap [ EnvMap, !Ref EnvironmentShort, val ]}

  PAInputTrigger:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda function that listens to pa data file uploads and triggers the step function
      FunctionName: !Sub 'CP-REF-etl-pa-trigger-${EnvironmentShort}'
      Runtime: python3.8
      Role: !GetAtt PAETLTriggerLambaRole.Arn
      Handler: s3_trigger_lambda.lambda_handler
      Code:
        S3Bucket: sysco-us-east-1-prcp-nonprod-codedeploy
        S3Key: ReferencePricingApi/DataPopulator/pa/scripts/s3_trigger_lambda.zip
      Environment:
        Variables:
          stepFunctionArn: !Ref PAStateMachine
      Timeout: 60

  PAStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub 'CP-REF-pa-state-machine-${EnvironmentShort}'
      StateMachineType: STANDARD
      DefinitionString: !Sub
        - |-
          {
          "Comment": "Transform and Loads PA data from S3 to DB",
          "StartAt": "PA ETL Job",
          "States": {
             "PA ETL Job": {
                "Type": "Task",
                "Resource": "arn:aws:states:::glue:startJobRun.sync",
                  "Parameters": {
                    "JobName": "${PADataETLJobName}",
                    "Arguments": {
                      "--s3_path.$": "$.s3_path"
                    }
                  },
                "Retry": [{
                  "ErrorEquals": ["States.TaskFailed"],
                  "IntervalSeconds": 3,
                  "MaxAttempts": 2,
                  "BackoffRate": 10}],
                "Catch": [{
                  "ErrorEquals": ["States.TaskFailed"],
                  "Next": "Load Job Failed"}
                ],
                "End": true
              },
              "Load Job Failed": {
                "Type": "Pass",
                "End": true
               }
            }
          }
        - PADataETLJobName: !Ref PAETLGlueJob
      LoggingConfiguration:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StepFunctionExecutionLogs.Arn
        IncludeExecutionData: TRUE
        Level: ALL
      RoleArn: !GetAtt PAETLStepFunctionExecutionRole.Arn

  StepFunctionExecutionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub 'step-function-execution-logs-${EnvironmentShort}'
      RetentionInDays: 30

  PAETLGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub 'CP-REF-etl-pa-job-${EnvironmentShort}'
      Description: Glue job to ETL pa data
      Command:
        Name: pythonshell
        PythonVersion: 3
        ScriptLocation: s3://sysco-us-east-1-prcp-nonprod-codedeploy/ReferencePricingApi/DataPopulator/pa/scripts/pa_etl_script.py
      Connections:
        Connections:
        - !Ref PADatabaseConnection
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-disable"
        "--extra-py-files": "s3://sysco-us-east-1-prcp-nonprod-codedeploy/ReferencePricingApi/DataPopulator/pa/libraries/PyMySQL-0.9.3-py2.py3-none-any.whl"
        "--GLUE_CONNECTION_NAME": !Ref PADatabaseConnection
        "--INTERMEDIATE_S3_BUCKET": !Ref IntermediateStorage
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxCapacity: 1.0
      MaxRetries: 0
      Timeout: 2880
      GlueVersion: 1.0
      Role: !GetAtt PAETLGlueRole.Arn

  PADatabaseConnection:
    Type: AWS::Glue::Connection
    Properties:
      CatalogId: !Ref AWS::AccountId
      ConnectionInput:
        ConnectionProperties: {
          "JDBC_CONNECTION_URL": !Ref PADatabaseJDBCUrl,
          "USERNAME": !Join ['', ["{{resolve:ssm:/CP/", !Ref EnvironmentShort, "/DATABASE/REF_PRICE/USERNAME:1}}"]],
          # SSM Secure reference is not supported in: [AWS::glue::Connection]
          "PASSWORD": !Ref PADatabasePassword
        }
        Description: Glue Connection to Referrence pricing database
        ConnectionType: JDBC
        Name: !Sub 'cp-ref-pa-etl-common-connection-${EnvironmentShort}'
        PhysicalConnectionRequirements:
          AvailabilityZone: !Ref AvailabilityZoneForGlueConnection
          SecurityGroupIdList: !Ref SecurityGroupListForGlueConnction
          SubnetId: !Ref SubnetIdForGlueConnection