AWSTemplateFormatVersion: 2010-09-09
Description: "Reference Price Data Populator for Price Zone data"
Parameters:
  EnvironmentShort:
    Description: Environment for application
    Type: String
    Default: DEV
    AllowedValues:
      - DEV
      - QA
      - STG
      - EXE
      - TST
      - PROD
    ConstraintDescription: Must be a valid environment
  NotifierLambdaSecutyGroup:
    Description: The list of Securty groups to use the Cloud Pricing Notification Service Api
    Type: List<AWS::EC2::SecurityGroup::Id>
    Default: sg-014f39d2fd8370bf6
  NotifierLambdaSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The list of Subnets to use the Cloud Pricing Notification Service Api
    Default: subnet-0a5d9eea71b9c97c6, subnet-0186b43162a344d9a, subnet-0ad1216eb31e15186
  IntermediateStorage:
    Description: S3 bucket name to store intermediate files
    Type: String
    Default: cp-ref-etl-output-bucket-dev
  SubnetIdForGlueConnection:
    Type: String
    Description: The subnetId to be referred
    Default: subnet-0ad1216eb31e15186
  AvailabilityZoneForGlueConnection:
    Type: String
    Description: The Availability Zone of the glue connection
    Default: us-east-1b
    AllowedValues:
      - us-east-1a
      - us-east-1b
      - us-east-1c
      - us-east-1d
      - us-east-1e
      - us-east-1f
  DatabaseJDBCUrl:
    Type: String
    Description: JDBC url of the database used to persist Reference pricing data
    Default: "jdbc:mysql://cp-ref-price-01-exe.c6xai0tt38eb.us-east-1.rds.amazonaws.com:3306/REF_PRICE_011"
  DatabasePassword:
    Type: String
    Description: Password of the database used for glue connection
    Default: ""
    NoEcho: true
  SecurityGroupListForGlueConnction:
    Type: CommaDelimitedList
    Description: Security group list for glue connection
    Default: sg-06a4893b70fc2f68f
  NotificationURL:
    Type: String
    Description: Cloud pricing Notification service URL
    Default: https://vpce-0ee878fea3ffd19c4-6bsoxvze.execute-api.us-east-1.vpce.amazonaws.com/stg/v1/cpns/notifications
  NotificationHost:
    Type: String
    Description: Cloud Pricing Notification service host
    Default: ivsgfq5vdl.execute-api.us-east-1.amazonaws.com
  PONumber:
    Description: PO Number for billing
    Type: String
    Default: '7000002358'
    MinLength: '1'
    MaxLength: '255'
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: Must contain only ASCII characters.
  ApplicationID:
    Description: Application ID - Official Application_ID, this is generated by Sysco's
      CMDB
    Type: String
    Default: APP-001151
    MinLength: '1'
    MaxLength: '255'
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: Must contain only ASCII characters.
  ApplicationName:
    Description: Application_Name - Common, user-friendly name
    Type: String
    Default: Cloud Pricing
    MinLength: '1'
    MaxLength: '255'
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: Must contain only ASCII characters.
  Approver:
    Description: Person approving instance funding.  This should be Email address
      formatted
    Type: String
    Default: villanueva.loi@corp.sysco.com
    MinLength: '1'
    MaxLength: '255'
  Owner:
    Description: Email address usually Product/ Platform Owner, though team distribution
      list for technical product/platform team contact
    Type: String
    Default: krishan.senevirathne@sysco.com
    MinLength: '1'
    MaxLength: '255'
  Component:
    Description: Component name
    Type: String
    Default: Reference Pricing Api
  SupportEmail:
    Description: Email distribution list for technical product/platform team contact
    Type: String
    Default: 000-BT-PricingPlatform@Corp.sysco.com
    MinLength: '1'
    MaxLength: '255'
  ProjectID:
    Description: Project_ID - BT Project ID for this workload
    Type: String
    Default: BT.001176
    MinLength: '1'
    MaxLength: '255'
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: Must contain only ASCII characters.
  2WTAGGER:
    Description: Used by 2nd Watch Managed Services in shared accounts to determine
      if a resource is supported
    Type: String
    Default: team-managed
    MinLength: '1'
    MaxLength: '255'
    AllowedValues:
      - team-managed
      - adlm-managed
      - 2w-managed
    ConstraintDescription: Must contain only ASCII characters.
  Platform:
    Description: Platform
    Type: String
    Default: Cloud Pricing V4

Mappings:
  EnvMap:
    DEV:
      val: dev
      name: Development
    QA:
      val: qa
      name: Quality
    STG:
      val: stg
      name: Staging
    EXE:
      val: exe
      name: Execution
    TST:
      val: tst
      name: Tuning
    PROD:
      val: prod
      name: Production

Resources:
  NotifierLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda function that use CPNS to notify
      FunctionName: !Sub 'CP-REF-etl-notifier-${EnvironmentShort}'
      Runtime: python3.8
      Role: !GetAtt ETLTriggerLambaRole.Arn
      Handler: index.lambda_handler
      Code:
        S3Bucket: sysco-us-east-1-prcp-nonprod-codedeploy
        S3Key: !Sub 'ReferencePricingApi/DataPopulator/${EnvironmentShort}/common_scripts/Notifier.zip'
      VpcConfig:
        SecurityGroupIds:
          !Ref NotifierLambdaSecutyGroup
        SubnetIds:
          !Ref NotifierLambdaSubnets
      Environment:
        Variables:
          env: !Ref EnvironmentShort
          cp_notification_url: !Ref NotificationURL
          cp_notification_host: !Ref NotificationHost
      Timeout: 120
      Tags:
        - Key: Technical:ApplicationName
          Value: !Ref ApplicationName
        - Key: Technical:ApplicationID
          Value: !Ref ApplicationID
        - Key: Technical:PlatformOwner
          Value: !Ref Owner
        - Key: Technical:Environment
          Value: !FindInMap [ EnvMap, !Ref EnvironmentShort, name ]
        - Key: Support_Email
          Value: !Ref SupportEmail
        - Key: Approver
          Value: !Ref Approver
        - Key: PO_Number
          Value: !Ref PONumber
        - Key: Project_ID
          Value: !Ref ProjectID
        - Key: 2WTAGGER
          Value: !Ref 2WTAGGER
        - Key: Platform
          Value: !Ref Platform
        - Key: Component
          Value: !Ref Component

  ETLTriggerLambaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'CP-REF-ETLTriggerLambaRole-${EnvironmentShort}'
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/PermissionBoundary-DevOps'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: CP-REF-StartStepFunctionExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                  - states:ListExecutions
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                  - ec2:DescribeInstances
                  - ec2:AttachNetworkInterface
                  - ssm:GetParameters
                  - ssm:GetParameter
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${IntermediateStorage}/*'
                  - !Sub 'arn:aws:s3:::${ETLDataBackUpStorage}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${IntermediateStorage}'
      Path: '/'

  ETLStepFunctionExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub 'CP-REF-ETLStepFunctionExecutionRole-${EnvironmentShort}'
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/PermissionBoundary-DevOps'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - !Sub 'states.${AWS::Region}.amazonaws.com'
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
      Policies:
        - PolicyName: CP-REF-ExecuteGlueJobPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - glue:GetJobs
                  - glue:BatchStopJobRun
                  - glue:ListJobs
                  - glue:CreateJob
                  - glue:BatchGetJobs
                  - glue:StartJobRun
                  - glue:GetJobRun
                  - glue:UpdateJob
                  - glue:GetJobRuns
                  - glue:GetJob
                Resource: "*"
        - PolicyName: LogStepFunctionEventPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:DescribeDestinations
                  - logs:PutDestination
                  - logs:CreateLogDelivery
                  - logs:GetLogDelivery
                  - logs:UpdateLogDelivery
                  - logs:DeleteLogDelivery
                  - logs:ListLogDeliveries
                  - logs:PutResourcePolicy
                  - logs:DescribeResourcePolicies
                  - logs:DescribeLogGroups
                Resource: '*'
      Path: '/'

  ETLGlueRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'CP-REF-ETLGlueRole-${EnvironmentShort}'
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/PermissionBoundary-DevOps'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'glue.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
        - !Sub 'arn:aws:iam::${AWS::AccountId}:policy/CloudPricing-IAM-SSM-Policy'
      Policies:
        - PolicyName: CP-REF-ETLGlueJobPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:CreateLogGroup
                  - logs:PutLogEvents
                  - logs:AssociateKmsKey
                Resource: 'arn:aws:logs:*:*:/aws-glue/*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - 'arn:aws:s3:::sysco-us-east-1-prcp-nonprod-codedeploy/ReferencePricingApi/*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub 'arn:aws:s3:::${IntermediateStorage}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${IntermediateStorage}'
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub
                  - 'arn:aws:s3:::cp-ref-etl-pa-data-storage-${env}/*'
                  - { env: !FindInMap [ EnvMap, !Ref EnvironmentShort, val ]}
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub
                  - 'arn:aws:s3:::cp-ref-etl-price-zone-storage-${env}/*'
                  - { env: !FindInMap [ EnvMap, !Ref EnvironmentShort, val ]}
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub
                  - 'arn:aws:s3:::cp-ref-etl-price-zone-spark-temp-dir-${env}/*'
                  - { env: !FindInMap [ EnvMap, !Ref EnvironmentShort, val ]}
      Path: '/'
  CommonDatabaseConnection:
    Type: AWS::Glue::Connection
    Properties:
      CatalogId: !Ref AWS::AccountId
      ConnectionInput:
        ConnectionProperties: {
          "JDBC_CONNECTION_URL": !Ref DatabaseJDBCUrl,
          "USERNAME": !Join ['', ["{{resolve:ssm:/CP/", !Ref EnvironmentShort, "/DATABASE/REF_PRICE/USERNAME:1}}"]],
          # SSM Secure reference is not supported in: [AWS::glue::Connection]
          "PASSWORD": !Ref DatabasePassword
        }
        Description: Glue Connection to Referrence pricing database
        ConnectionType: JDBC
        Name: !Sub 'cp-ref-etl-common-connection-${EnvironmentShort}'
        PhysicalConnectionRequirements:
          AvailabilityZone: !Ref AvailabilityZoneForGlueConnection
          SecurityGroupIdList: !Ref SecurityGroupListForGlueConnction
          SubnetId: !Ref SubnetIdForGlueConnection

  ETLDataBackUpStorage:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub
        - 'cp-ref-etl-data-backup-storage-${env}'
        - { env: !FindInMap [ EnvMap, !Ref EnvironmentShort, val ]}
      LifecycleConfiguration:
        Rules:
          - Transitions:
              - StorageClass: GLACIER
                TransitionInDays: 30
            Id: Transition-To-Glacier-Rule
            Status: Enabled
      Tags:
        - Key: Technical:ApplicationName
          Value: !Ref ApplicationName
        - Key: Technical:ApplicationID
          Value: !Ref ApplicationID
        - Key: Technical:PlatformOwner
          Value: !Ref Owner
        - Key: Technical:Environment
          Value: !FindInMap [ EnvMap, !Ref EnvironmentShort, name ]
        - Key: Support_Email
          Value: !Ref SupportEmail
        - Key: Approver
          Value: !Ref Approver
        - Key: PO_Number
          Value: !Ref PONumber
        - Key: Project_ID
          Value: !Ref ProjectID
        - Key: 2WTAGGER
          Value: !Ref 2WTAGGER
        - Key: Platform
          Value: !Ref Platform
        - Key: Component
          Value: !Ref Component

  MetadataAggregatorLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda function that collects metadata
      FunctionName: !Sub 'CP-REF-PRICE-etl-metadata-aggregator-${EnvironmentShort}'
      Runtime: python3.8
      Role: !GetAtt ETLTriggerLambaRole.Arn
      Handler: metadata_aggregator.lambda_handler
      Code:
        S3Bucket: sysco-us-east-1-prcp-nonprod-codedeploy
        S3Key: !Sub 'ReferencePricingApi/DataPopulator/${EnvironmentShort}/common_scripts/metadata_aggregator.py.zip'
      VpcConfig:
        SecurityGroupIds:
          !Ref NotifierLambdaSecutyGroup
        SubnetIds:
          !Ref NotifierLambdaSubnets
      Environment:
        Variables:
          env: !Ref EnvironmentShort
      Timeout: 60
      Tags:
        - Key: Technical:ApplicationName
          Value: !Ref ApplicationName
        - Key: Technical:ApplicationID
          Value: !Ref ApplicationID
        - Key: Technical:PlatformOwner
          Value: !Ref Owner
        - Key: Technical:Environment
          Value: !FindInMap [ EnvMap, !Ref EnvironmentShort, name ]
        - Key: Support_Email
          Value: !Ref SupportEmail
        - Key: Approver
          Value: !Ref Approver
        - Key: PO_Number
          Value: !Ref PONumber
        - Key: Project_ID
          Value: !Ref ProjectID
        - Key: 2WTAGGER
          Value: !Ref 2WTAGGER
        - Key: Platform
          Value: !Ref Platform
        - Key: Component
          Value: !Ref Component

  ETLDataBackUpGlueRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'CP-REF-ETLDataBackupGlueRole-${EnvironmentShort}'
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/PermissionBoundary-DevOps'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'glue.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: CP-REF-ETLDataBackupGlueJobPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:CreateLogGroup
                  - logs:PutLogEvents
                  - logs:AssociateKmsKey
                Resource: 'arn:aws:logs:*:*:/aws-glue/*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - 'arn:aws:s3:::sysco-us-east-1-prcp-nonprod-codedeploy/ReferencePricingApi/*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:DeleteObject
                Resource:
                  - !Sub 'arn:aws:s3:::${IntermediateStorage}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${IntermediateStorage}'
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:DeleteObject
                Resource: !Sub
                  - 'arn:aws:s3:::cp-ref-etl-pa-data-storage-${env}/*'
                  - { env: !FindInMap [ EnvMap, !Ref EnvironmentShort, val ]}
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:DeleteObject
                Resource: !Sub
                  - 'arn:aws:s3:::cp-ref-etl-price-zone-storage-${env}/*'
                  - { env: !FindInMap [ EnvMap, !Ref EnvironmentShort, val ]}
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub 'arn:aws:s3:::${ETLDataBackUpStorage}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${ETLDataBackUpStorage}'
      Path: '/'

Outputs:
  CommonDBConnectionName:
    Description: Reference price common glue database connection
    Value: !Ref CommonDatabaseConnection
  ETLGlueRoleArn:
    Description: ETL glue role arn
    Value: !GetAtt ETLGlueRole.Arn
  ETLStepFunctionExecutionRoleArn:
    Description: ETL step function execution role arn
    Value: !GetAtt ETLStepFunctionExecutionRole.Arn
  ETLTriggerLambaRoleArn:
    Description: ETL trigger lambda role arn
    Value: !GetAtt ETLTriggerLambaRole.Arn
  NotifierLambdaArn:
    Description: Common lambda notifier arn
    Value: !GetAtt NotifierLambda.Arn
  ETLDataBackUpGlueRole:
    Description: ETL Data backup glue role
    Value: !GetAtt ETLDataBackUpGlueRole.Arn
  ETLDataBackUpStorage:
    Description: S3 bucket to archive ETL related files
    Value: !Ref ETLDataBackUpStorage
