AWSTemplateFormatVersion: 2010-09-09
Description: "Reference Price PA Data Populator"
Parameters:
  LambdaRole:
    Description: ARN of the iam role for the lambda function
    Type: String
    Default: arn:aws:iam::037295147636:role/CP-REF-ETLTriggerLambaRole-DEV
  StepFuctionExecutionRole:
      Description: ARN of the iam role for the step function
      Type: String
      Default: arn:aws:iam::037295147636:role/CP-REF-ETLStepFunctionExecutionRole-DEV
  GlueJobExecutionRole:
      Description: ARN of the iam role for the glue job
      Type: String
      Default: arn:aws:iam::037295147636:role/CP-REF-ETLGlueRole-DEV
  GlueJobDataBackupRole:
    Description: ARN of the iam role for the glue job to backup data
    Type: String
    Default: arn:aws:iam::037295147636:role/CP-REF-ETLDataBackupGlueRole-DEV
  DatabaseConnection:
    Description: Name of the databse connection
    Type: String
    Default: cp-ref-etl-output-bucket-dev
  IntermediateStorage:
    Description: S3 bucket name to store intermediate files
    Type: String
    Default: cp-ref-etl-output-bucket-dev
  ETLDataBackUpStorage:
    Description: S3 bucket to archive files
    Type: String
  EnvironmentShort:
    Description: Environment for application
    Type: String
    Default: DEV
    AllowedValues:
      - DEV
      - QA
      - STG
      - EXE
      - TST
      - PROD
    ConstraintDescription: Must be a valid environment
  NotifierLambdaArn:
    Description: Arn of the notifier Lambda
    Type: String
    Default: arn:aws:lambda:us-east-1:037295147636:function:CP-REF-etl-notifier-DEV
  PONumber:
    Description: PO Number for billing
    Type: String
    Default: '7000002358'
    MinLength: '1'
    MaxLength: '255'
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: Must contain only ASCII characters.
  ApplicationID:
    Description: Application ID - Official Application_ID, this is generated by Sysco's
      CMDB
    Type: String
    Default: APP-001151
    MinLength: '1'
    MaxLength: '255'
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: Must contain only ASCII characters.
  ApplicationName:
    Description: Application_Name - Common, user-friendly name
    Type: String
    Default: Cloud Pricing
    MinLength: '1'
    MaxLength: '255'
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: Must contain only ASCII characters.
  Approver:
    Description: Person approving instance funding.  This should be Email address
      formatted
    Type: String
    Default: villanueva.loi@corp.sysco.com
    MinLength: '1'
    MaxLength: '255'
  Owner:
    Description: Email address usually Product/ Platform Owner, though team distribution
      list for technical product/platform team contact
    Type: String
    Default: krishan.senevirathne@sysco.com
    MinLength: '1'
    MaxLength: '255'
  Component:
    Description: Component name
    Type: String
    Default: Reference Pricing Api
  SupportEmail:
    Description: Email distribution list for technical product/platform team contact
    Type: String
    Default: 000-BT-PricingPlatform@Corp.sysco.com
    MinLength: '1'
    MaxLength: '255'
  ProjectID:
    Description: Project_ID - BT Project ID for this workload
    Type: String
    Default: BT.001176
    MinLength: '1'
    MaxLength: '255'
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: Must contain only ASCII characters.
  2WTAGGER:
    Description: Used by 2nd Watch Managed Services in shared accounts to determine
      if a resource is supported
    Type: String
    Default: team-managed
    MinLength: '1'
    MaxLength: '255'
    AllowedValues:
      - team-managed
      - adlm-managed
      - 2w-managed
    ConstraintDescription: Must contain only ASCII characters.
  Platform:
    Description: Platform
    Type: String
    Default: Cloud Pricing V4

Mappings:
  EnvMap:
    DEV:
      val: dev
      name: Development
    QA:
      val: qa
      name: Quality
    STG:
      val: stg
      name: Staging
    EXE:
      val: exe
      name: Execution
    TST:
      val: tst
      name: Tuning
    PROD:
      val: prod
      name: Production

Resources:
  PADataStorage:
    DependsOn: LambdaInvokePermission
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub
        - 'cp-ref-etl-pa-data-storage-${env}'
        - { env: !FindInMap [ EnvMap, !Ref EnvironmentShort, val ]}
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt PAInputTriggerLambda.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: gz
      Tags:
        - Key: Technical:ApplicationName
          Value: !Ref ApplicationName
        - Key: Technical:ApplicationID
          Value: !Ref ApplicationID
        - Key: Technical:PlatformOwner
          Value: !Ref Owner
        - Key: Technical:Environment
          Value: !FindInMap [ EnvMap, !Ref EnvironmentShort, name ]
        - Key: Support_Email
          Value: !Ref SupportEmail
        - Key: Approver
          Value: !Ref Approver
        - Key: PO_Number
          Value: !Ref PONumber
        - Key: Project_ID
          Value: !Ref ProjectID
        - Key: 2WTAGGER
          Value: !Ref 2WTAGGER
        - Key: Platform
          Value: !Ref Platform
        - Key: Component
          Value: !Ref Component

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt PAInputTriggerLambda.Arn
      Principal: s3.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !Sub
        - 'arn:aws:s3:::cp-ref-etl-pa-data-storage-${env}'
        - { env: !FindInMap [ EnvMap, !Ref EnvironmentShort, val ]}

  PAInputTriggerLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda function that listens to pa data file uploads and triggers the step function
      FunctionName: !Sub 'CP-REF-etl-pa-trigger-${EnvironmentShort}'
      Runtime: python3.8
      Role: !Ref LambdaRole
      Handler: s3_trigger_lambda.lambda_handler
      Code:
        S3Bucket: sysco-us-east-1-prcp-nonprod-codedeploy
        S3Key: !Sub 'ReferencePricingApi/DataPopulator/${EnvironmentShort}/pa/scripts/s3_trigger_lambda.zip'
      Environment:
        Variables:
          stepFunctionArn: !Ref PAStateMachine
      Timeout: 60
      Tags:
        - Key: Technical:ApplicationName
          Value: !Ref ApplicationName
        - Key: Technical:ApplicationID
          Value: !Ref ApplicationID
        - Key: Technical:PlatformOwner
          Value: !Ref Owner
        - Key: Technical:Environment
          Value: !FindInMap [ EnvMap, !Ref EnvironmentShort, name ]
        - Key: Support_Email
          Value: !Ref SupportEmail
        - Key: Approver
          Value: !Ref Approver
        - Key: PO_Number
          Value: !Ref PONumber
        - Key: Project_ID
          Value: !Ref ProjectID
        - Key: 2WTAGGER
          Value: !Ref 2WTAGGER
        - Key: Platform
          Value: !Ref Platform
        - Key: Component
          Value: !Ref Component

  PADataBackupJob:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: pythonshell
        PythonVersion: 3
        ScriptLocation: !Sub 's3://sysco-us-east-1-prcp-nonprod-codedeploy/ReferencePricingApi/DataPopulator/${EnvironmentShort}/pa/scripts/data_backup_job.py'
      DefaultArguments:
        "--INTERMEDIATE_S3_BUCKET": !Ref IntermediateStorage
        "--ARCHIVING_S3_BUCKET": !Ref ETLDataBackUpStorage
        "--extra-py-files": !Sub "s3://sysco-us-east-1-prcp-nonprod-codedeploy/ReferencePricingApi/DataPopulator/${EnvironmentShort}/common_scripts/move_s3_objects.py"
      ExecutionProperty:
        MaxConcurrentRuns: 1
      GlueVersion: 1.0
      MaxRetries: 0
      MaxCapacity: 1.0
      Name: !Sub 'CP-REF-etl-pa-backup-job-${EnvironmentShort}'
      Role: !Ref GlueJobDataBackupRole
      Tags: {
        'Technical:ApplicationName': !Ref ApplicationName,
        'Technical:ApplicationID': !Ref ApplicationID,
        'Technical:PlatformOwner': !Ref Owner,
        'Technical:Environment': !FindInMap [ EnvMap, !Ref EnvironmentShort, name ],
        'Support_Email': !Ref SupportEmail,
        'Approver': !Ref Approver,
        'PO_Number': !Ref PONumber,
        'Project_ID': !Ref ProjectID,
        '2WTAGGER': !Ref 2WTAGGER,
        'Platform': !Ref Platform,
        'Component': !Ref Component
      }

  PAStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub 'CP-REF-pa-state-machine-${EnvironmentShort}'
      StateMachineType: STANDARD
      DefinitionString: !Sub
        - |-
          {
            "Comment": "Transform and Loads PA data from S3 to DB",
            "StartAt": "PA ETL Job",
            "States": {
              "PA ETL Job": {
                "Type": "Task",
                "Resource": "arn:aws:states:::glue:startJobRun.sync",
                "Parameters": {
                  "JobName": "${PADataETLJobName}",
                  "Arguments": {
                    "--s3_input_bucket.$": "$.s3_input_bucket",
                    "--s3_input_file_key.$": "$.s3_input_file_key",
                    "--etl_output_path_key.$": "$.etl_output_path_key",
                    "--etl_timestamp.$": "$.etl_timestamp"
                  }
                },
                "Retry": [
                  {
                    "ErrorEquals": [
                      "States.TaskFailed"
                    ],
                    "IntervalSeconds": 3,
                    "MaxAttempts": 1,
                    "BackoffRate": 10
                  }
                ],
                "Catch": [
                  {
                    "ErrorEquals": [
                      "States.TaskFailed"
                    ],
                    "ResultPath": "$.error",
                    "Next": "Notify ETL Failure"
                  }
                ],
                "ResultPath": "$.response",
                "Next": "Backup Data"
              },
              "Backup Data": {
                "Comment": "Backup data python shell job",
                "Type": "Task",
                "Resource": "arn:aws:states:::glue:startJobRun.sync",
                "Parameters": {
                  "JobName": "${paDataBackupJobName}",
                  "Arguments": {
                    "--s3_input_bucket.$": "$.s3_input_bucket",
                    "--s3_input_file_key.$": "$.s3_input_file_key",
                    "--etl_timestamp.$": "$.etl_timestamp",
                    "--etl_output_path_key.$": "$.etl_output_path_key"
                  }
                },
                "ResultPath": "$.response",
                "Catch": [
                  {
                    "ErrorEquals": [
                      "States.TaskFailed"
                    ],
                    "ResultPath": "$.error",
                    "Next": "Notify ETL Failure"
                  }
                ],
                "Next": "Notify ETL Success"
              },
              "Notify ETL Failure": {
                "Type": "Task",
                "Resource": "arn:aws:states:::lambda:invoke",
                "Parameters": {
                  "FunctionName": "${notifierLambdaArn}",
                  "Payload": {
                    "event": "ETL-PA",
                    "message.$": "$.error.Cause"
                  }
                },
                "End": true
              },
              "Notify ETL Success": {
                "Type": "Task",
                "Resource": "arn:aws:states:::lambda:invoke",
                "Parameters": {
                  "FunctionName": "${notifierLambdaArn}",
                  "Payload": {
                    "event": "[ETL] - [Ref Price] [Price Data]",
                    "message.$": "States.Format('S3 Path: {}, ETL timestamp: {}, Execution Id: {}', $.s3_path, $.etl_timestamp, $$.Execution.Id)",
                    "status": "SUCCEEDED"
                  }
                },
                "End": true
              }
            }
          }
        - {
            PADataETLJobName: !Ref PAETLGlueJob,
            notifierLambdaArn: !Ref NotifierLambdaArn,
            paDataBackupJobName: !Ref PADataBackupJob
        }
      LoggingConfiguration:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt PAStepFunctionExecutionLogs.Arn
        IncludeExecutionData: TRUE
        Level: ALL
      RoleArn: !Ref StepFuctionExecutionRole
      Tags:
        - Key: Technical:ApplicationName
          Value: !Ref ApplicationName
        - Key: Technical:ApplicationID
          Value: !Ref ApplicationID
        - Key: Technical:PlatformOwner
          Value: !Ref Owner
        - Key: Technical:Environment
          Value: !FindInMap [ EnvMap, !Ref EnvironmentShort, name ]
        - Key: Support_Email
          Value: !Ref SupportEmail
        - Key: Approver
          Value: !Ref Approver
        - Key: PO_Number
          Value: !Ref PONumber
        - Key: Project_ID
          Value: !Ref ProjectID
        - Key: 2WTAGGER
          Value: !Ref 2WTAGGER
        - Key: Platform
          Value: !Ref Platform
        - Key: Component
          Value: !Ref Component

  PAStepFunctionExecutionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub 'cp-ref-etl-pa-step-function-logs-${EnvironmentShort}'
      RetentionInDays: 30

  PAETLGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub 'CP-REF-etl-pa-job-${EnvironmentShort}'
      Description: Glue job to ETL pa data
      Command:
        Name: pythonshell
        PythonVersion: 3
        ScriptLocation: !Sub 's3://sysco-us-east-1-prcp-nonprod-codedeploy/ReferencePricingApi/DataPopulator/${EnvironmentShort}/pa/scripts/pa_etl_script.py'
      Connections:
        Connections:
          - !Ref DatabaseConnection
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-disable"
        "--extra-py-files": !Sub "s3://sysco-us-east-1-prcp-nonprod-codedeploy/ReferencePricingApi/DataPopulator/${EnvironmentShort}/pa/libraries/PyMySQL-0.9.3-py2.py3-none-any.whl"
        "--GLUE_CONNECTION_NAME": !Ref DatabaseConnection
        "--INTERMEDIATE_S3_BUCKET": !Ref IntermediateStorage
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxCapacity: 1.0
      MaxRetries: 0
      Timeout: 2880
      GlueVersion: 1.0
      Role: !Ref GlueJobExecutionRole
      Tags: {
        'Technical:ApplicationName': !Ref ApplicationName,
        'Technical:ApplicationID': !Ref ApplicationID,
        'Technical:PlatformOwner': !Ref Owner,
        'Technical:Environment': !FindInMap [ EnvMap, !Ref EnvironmentShort, name ],
        'Support_Email': !Ref SupportEmail,
        'Approver': !Ref Approver,
        'PO_Number': !Ref PONumber,
        'Project_ID': !Ref ProjectID,
        '2WTAGGER': !Ref 2WTAGGER,
        'Platform': !Ref Platform,
        'Component': !Ref Component
      }
