AWSTemplateFormatVersion: 2010-09-09
Description: This is the stack for CP Mimix Daily Purge Sync Job Definition
Parameters:
  EnvironmentShort:
    Description: Environment for application
    Type: String
    Default: PROD
    AllowedValues:
      - PROD
  EmailSubject:
    Description: Subject for alert emails
    Type: String
    Default: MIMIX-Purging-Alerts-PROD
  TaskRole:
    Description: ARN of task role attached to ECS task.
    Type: String
    Default: arn:aws:iam::130227353653:role/CloudPricing-Mimix-Purge-Job-Role

Resources:
  JobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      JobDefinitionName:
        Fn::Join:
          - ''
          - - CP-Mimix-Purge-Job-Definition-
            - Ref: 'EnvironmentShort'
      RetryStrategy:
        Attempts: 1
      Timeout:
        AttemptDurationSeconds: 10800
      PlatformCapabilities:
        - FARGATE
      ContainerProperties:
        Image: '130227353653.dkr.ecr.us-east-1.amazonaws.com/cp-query-sync:latest'
        ResourceRequirements:
          - Type: VCPU
            Value: 4
          - Type: MEMORY
            Value: 8192
        ExecutionRoleArn: !Ref TaskRole
        Command:
          - java
          - "-Xmx6144M"
          - "-jar"
          - mimix-query-syncing-processor.jar
          - Ref::business_unit
        JobRoleArn: !Ref 'TaskRole'
        Environment:
          - Name: 'SERVER_ENVIRONMENT_VARIABLE'
            Value: !Ref 'EnvironmentShort'
          - Name: 'SENDER'
            Value: 'CloudPricingAlerts@corp.sysco.com'
          - Name: 'SUBJECT'
            Value: !Ref 'EmailSubject'
          - Name: 'TO_ADDRESSES'
            Value: 'sanjaya.amarasinghe@syscolabs.com,shetty.vidyasagar@corp.sysco.com,villanueva.loi@corp.sysco.com,amoda.dissanayake@sysco.com,chamin.wickramarathna@sysco.com,
            gayan.herath@sysco.com,asanka.indunil@corp.sysco.com,gothami.karunarathna@syscolabs.com,piyumi.rameshka@sysco.com,
            muqshid.mohamed@syscolabs.com,jayani.gajanayake@syscolabs.com,chandima.samarasinghe@syscolabs.com,chathurangi.edussuriya@syscolabs.com,
            sahan.jayawardena@syscolabs.com,osanda.hemachandra@syscolabs.com,chandika.herath@syscolabs.com'
