AWSTemplateFormatVersion: 2010-09-09
Description: Stack for Outlier Price Range Resources.  
Parameters:
  Environment:
    Description: Environment for application
    Type: String
    Default: EXE
    AllowedValues:
      - DEV
      - EXE
      - QA
      - STG
      - PROD
      - NONPROD
    ConstraintDescription: Must be a valid environment.
  ExecutionRole:
    Description: ARN of execution role attached to ECS task.
    Type: String
    Default: arn:aws:iam::037295147636:role/CloudPricing-Batch-IAM-Job-Role
  TaskRole:
    Description: ARN of task role attached to ECS task.
    Type: String
    Default: arn:aws:iam::037295147636:role/CloudPricing-Batch-IAM-Job-Role
  RoleArn:
    Description: ARN of task role attached to cloud watch Events.
    Type: String
    Default: arn:aws:iam::037295147636:role/Princing-Web-Service-Role
  DockerImageArn:
    Description: Docker image of outlier price range
    Type: String
    Default: 037295147636.dkr.ecr.us-east-1.amazonaws.com/cp-outlier-price-range
  CPUForTask:
    Description: The number of cpu units reserved for the task.
    Type: Number
    Default: '1024'
    MinValue: '256'
    MaxValue: '4096'
  CPUForContainer:
    Description: The number of cpu units reserved for the container.
    Type: Number
    Default: '512'
    MinValue: '256'
    MaxValue: '4096'
  MemoryForTask:
    Description: The soft limit (in MiB) of memory to reserve for the task.
    Type: Number
    Default: '2048'
    MinValue: '256'
    MaxValue: '8192'
  MemoryForContainer:
    Description: The soft limit (in MiB) of memory to reserve for the container.
    Type: Number
    Default: '1024'
    MinValue: '256'
    MaxValue: '8192'
  PvtSNa:
    Description: 'Private PRCP-NP Confidential Subnet 1 in us-east-1a CIDR: 10.132.88.0/24'
    Type: String
    Default: subnet-0186b43162a344d9a
  PvtSNb:
    Description: 'Private PRCP-NP Confidential Subnet 2 in us-east-1b CIDR: 10.132.89.0/24'
    Type: String
    Default: subnet-0ad1216eb31e15186
  PvtSNc:
    Description: 'Private PRCP-NP Confidential Subnet 3 in us-east-1c CIDR: 10.132.89.0/24'
    Type: String
    Default: subnet-0a5d9eea71b9c97c6
  VPCID:
    Description: Name of an existing VPC
    Type: String
    Default: vpc-091c7e3e5578d7a4f
  SGECS:
    Description: Security group with ECS Allowed Ports
    Type: String
    Default: sg-0d9f433edb4677f08
  RetentionTime:
    Description: The number of days to retain the log events in the specified log group. Possible values are 1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, and 3653.
    Type: Number
    Default: '30'
    MinValue: '1'
    MaxValue: '3653'

Resources:

  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: !Join
        - ''
        - - 'CP-iOPR-Data-Creation-Cluster-'
          - !Ref 'Environment'
    
  DataCreationTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Cpu: !Ref CPUForTask
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      Family: !Join
        - ''
        - - 'CP-iOPR-Data-Creation-Task-Definition-'
          - !Ref 'Environment'
      Memory: !Ref MemoryForTask
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
      - Essential: true
        Image: !Ref DockerImageArn
        Name: cp-iopr-data-creation
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: !Ref LogGroup
            awslogs-region: !Ref 'AWS::Region'
            awslogs-stream-prefix: ecs/iOPR
        PortMappings:
          - {ContainerPort: 80}
          - {ContainerPort: 5439}
        Environment:
          - Name: SERVER_ENVIRONMENT_VARIABLE
            Value: !Ref Environment
    DependsOn:
    - ECSCluster

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join
        - ''
        - - '/aws/ecs/CP-iOPR-Data-Creation-'
          - !Ref 'Environment'
      RetentionInDays: !Ref RetentionTime

  ScheduleRule1To5:
    Type: AWS::Events::Rule
    Properties:
      Description: "Schedule rule for opco 001 - 005"
      Name: !Join
        - ''
        - - 'Price-Range-001-005-'
          - !Ref 'Environment'
      State: DISABLED
      ScheduleExpression: 'cron(30 1 ? * THU *)'
      RoleArn: !Ref RoleArn
      Targets:
        - Arn: !GetAtt
            - ECSCluster
            - Arn
          Id: ScheduledTask
          RoleArn: !Ref RoleArn
          Input: '{ "containerOverrides": [{"name": "cp-iopr-data-creation", "environment": [{"name": "BUSINESS_UNITS","value": "001, 002, 003, 004, 005"}]}]}'
          EcsParameters:
            TaskDefinitionArn: !Ref 'DataCreationTaskDefinition'
            LaunchType: FARGATE
            NetworkConfiguration:
              AwsVpcConfiguration:
                AssignPublicIp: DISABLED
                SecurityGroups:
                - !Ref 'SGECS' 
                Subnets:
                - !Ref 'PvtSNa'
                - !Ref 'PvtSNb'
                - !Ref 'PvtSNc'

  ScheduleRule55To57:
    Type: AWS::Events::Rule
    Properties:
      Description: "Schedule rule for opco 055 - 057"
      Name: !Join
        - ''
        - - 'Price-Range-055-057-'
          - !Ref 'Environment'
      State: ENABLED
      ScheduleExpression: 'cron(00 17 ? * WED *)'
      RoleArn: !Ref RoleArn
      Targets:
        - Arn: !GetAtt
            - ECSCluster
            - Arn
          Id: ScheduledTask
          RoleArn: !Ref RoleArn
          Input: '{ "containerOverrides": [{"name": "cp-iopr-data-creation", "environment": [{"name": "BUSINESS_UNITS","value": "055, 056, 057"}]}]}'
          EcsParameters:
            TaskDefinitionArn: !Ref 'DataCreationTaskDefinition'
            LaunchType: FARGATE
            NetworkConfiguration:
              AwsVpcConfiguration:
                AssignPublicIp: DISABLED
                SecurityGroups:
                - !Ref 'SGECS' 
                Subnets:
                - !Ref 'PvtSNa'
                - !Ref 'PvtSNb'
                - !Ref 'PvtSNc'

  ScheduleRule66To68:
    Type: AWS::Events::Rule
    Properties:
      Description: "Schedule rule for opco 066 - 068"
      Name: !Join
        - ''
        - - 'Price-Range-066-068-'
          - !Ref 'Environment'
      State: ENABLED
      ScheduleExpression: 'cron(15 17 ? * WED *)'
      RoleArn: !Ref RoleArn
      Targets:
        - Arn: !GetAtt
            - ECSCluster
            - Arn
          Id: ScheduledTask
          RoleArn: !Ref RoleArn
          Input: '{ "containerOverrides": [{"name": "cp-iopr-data-creation", "environment": [{"name": "BUSINESS_UNITS","value": "066, 067, 068"}]}]}'
          EcsParameters:
            TaskDefinitionArn: !Ref 'DataCreationTaskDefinition'
            LaunchType: FARGATE
            NetworkConfiguration:
              AwsVpcConfiguration:
                AssignPublicIp: DISABLED
                SecurityGroups:
                - !Ref 'SGECS' 
                Subnets:
                - !Ref 'PvtSNa'
                - !Ref 'PvtSNb'
                - !Ref 'PvtSNc'

Outputs:
  DataCreationTaskDefinition:
    Description: The Cp Data Creation Task Definition ARN
    Value: !Ref DataCreationTaskDefinition
  ClusterARN:
    Description: The ECS Cluster ARN
    Value: !GetAtt ECSCluster.Arn

