AWSTemplateFormatVersion: 2010-09-09
Description: "SSM Parameters for CIPZ"
Parameters:
  environment:
    Description: Name of the environment
    Type: String
    Default: DEV
    AllowedValues:
      - DEV
      - QE
      - EXE
      - STG
      - PROD
  paramStoreConfigPrefix:
    Type: String
    Default: "/CP/CIPZ_SERVICE"
  DBMasterUsernameValue:
    Type: String
    Description: DB Master username
    Default: "cpuser"
  DBCIPZNameValue:
    Type: String
    Description: CIPZ DB name
    Default: "PriceZoneReassignments"
  ConfigMaxLifeLowerLimitValue:
    Type: String
    Default: "3000"
    Description: Lower limit of the connection pool max life and max idle time
  ConfigMaxLifeUpperLimitValue:
    Type: String
    Default: "210000"
    Description: Upper limit of the connection pool max life and max idle time
  ConfigReaderMaxPoolSizeValue:
    Type: String
    Default: "40"
    Description: Maximum number of connections per opco pool for reader
  ConfigReaderInitialPoolSizeValue:
    Type: String
    Default: "10"
    Description: Initial number of connections per opco pool for reader
  ConfigWriterMaxPoolSizeValue:
    Type: String
    Default: "10"
    Description: Maximum number of connections per opco pool for writer
  ConfigWriterInitialPoolSizeValue:
    Type: String
    Default: "2"
    Description: Initial number of connections per opco pool for writer
  ActiveBusinessUnitsValue:
    Type: String
    Default: "019"
    Description: Active business units
  AuthorizedClientsValue:
    Type: String
    Default: "cloud-pci-bff"
    Description: Authorized Clients ID
  SeedApiTimeoutValue:
    Type: String
    Default: "2000"
    Description: Seed API timeout
  SeedApiPaginationLimit:
    Type: String
    Default: "100"
    Description: Pagination limit
  SeedApiHost:
    Type: String
    Default: "http://internal-cp-cipz-seed-mock-api-alb-dev-448991051.us-east-1.elb.amazonaws.com/"
    Description: Seed API host
  SeedApiServiceUrl:
    Type: String
    Default: "services/v1/edwp/"
    Description: Seed API Service URL path
  SeedCustomerPZEndpoint:
    Type: String
    Default: "item-price-zone/customer-attribute-group"
    Description: Customer PZ Endpoint
  SeedCustomerGroupPZEndpoint:
    Type: String
    Default: "item-price-zone/customer-group-attribute-group"
    Description: Customer Group PZ Endpoint
Resources:
  DBMasterUserName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["/", [!Ref paramStoreConfigPrefix, !Ref environment, CIPZ/DB/USERNAME]]
      Type: String
      Description: DB Master username
      Value: !Ref DBMasterUsernameValue
  DBCIPZName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ "/", [ !Ref paramStoreConfigPrefix, !Ref environment, CIPZ/DB/NAME ] ]
      Type: String
      Description: CIPZ DB name
      Value: !Ref DBCIPZNameValue
  ConfigMaxLifeLowerLimit:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["/", [!Ref paramStoreConfigPrefix, !Ref environment, CIPZ/DB/MAX/LIFE/LOWER/LIMIT]]
      Type: String
      Description: Lower limit of the connection pool max life and max idle time
      Value: !Ref ConfigMaxLifeLowerLimitValue
  ConfigMaxLifeUpperLimit:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["/", [!Ref paramStoreConfigPrefix, !Ref environment, CIPZ/DB/MAX/LIFE/UPPER/LIMIT]]
      Type: String
      Description: Upper limit of the connection pool max life and max idle time
      Value: !Ref ConfigMaxLifeUpperLimitValue
  ConfigReaderMaxPoolSize:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["/", [!Ref paramStoreConfigPrefix, !Ref environment, CIPZ/DB/READER/MAX/POOL/SIZE]]
      Type: String
      Description: Maximum number of connections per opco pool for reader
      Value: !Ref ConfigReaderMaxPoolSizeValue
  ConfigReaderInitialPoolSize:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["/", [!Ref paramStoreConfigPrefix, !Ref environment, CIPZ/DB/READER/INITIAL/POOL/SIZE]]
      Type: String
      Description: Initial number of connections per opco pool for reader
      Value: !Ref ConfigReaderInitialPoolSizeValue
  ConfigWriterMaxPoolSize:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["/", [!Ref paramStoreConfigPrefix, !Ref environment, CIPZ/DB/MAX/WRITER/POOL/SIZE]]
      Type: String
      Description: Maximum number of connections per opco pool for writer
      Value: !Ref ConfigWriterMaxPoolSizeValue
  ConfigWriterInitialPoolSize:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["/", [!Ref paramStoreConfigPrefix, !Ref environment, CIPZ/DB/WRITER/INITIAL/POOL/SIZE]]
      Type: String
      Description: Initial number of connections per opco pool for writer
      Value: !Ref ConfigWriterInitialPoolSizeValue
  ActiveBusinessUnits:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["/", [!Ref paramStoreConfigPrefix, !Ref environment, ACTIVE/BUSINESS/UNITS]]
      Type: String
      Description: Active business units
      Value: !Ref ActiveBusinessUnitsValue
  AuthorizedClients:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["/", [!Ref paramStoreConfigPrefix, !Ref environment, AUTHORIZED/CLIENTS]]
      Type: String
      Description: Authorized clients for the customer CIPZs endpoint
      Value: !Ref AuthorizedClientsValue
  SEEDAPITimeout:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["/", [!Ref paramStoreConfigPrefix, !Ref environment, SEED/API/TIMEOUT]]
      Type: String
      Description: Seed API timeout
      Value: !Ref SeedApiTimeoutValue
  SEEDAPIPaginationLimit:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["/", [!Ref paramStoreConfigPrefix, !Ref environment, SEED/API/PAGINATION/LIMIT]]
      Type: String
      Description: Seed API pagination limit
      Value: !Ref SeedApiPaginationLimit
  SEEDAPIHostUrl:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["/", [!Ref paramStoreConfigPrefix, !Ref environment, SEED/API/HOST]]
      Type: String
      Description: Seed API host url
      Value: !Ref SeedApiHost
  SEEDAPIServiceUrl:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["/", [!Ref paramStoreConfigPrefix, !Ref environment, SEED/API/SERVICE/URL]]
      Type: String
      Description: Seed API Service URI path
      Value: !Ref SeedApiServiceUrl
  SEEDAPICustomerPZEndpoint:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["/", [!Ref paramStoreConfigPrefix, !Ref environment, SEED/API/ENDPOINT/CUSTOMER/PRICE_ZONE_DETAILS]]
      Type: String
      Description: Customer PZ Endpoint
      Value: !Ref SeedCustomerPZEndpoint
  SEEDAPICustomerGroupPZEndpoint:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["/", [!Ref paramStoreConfigPrefix, !Ref environment, SEED/API/ENDPOINT/CUSTOMER_GROUP/PRICE_ZONE_DETAILS]]
      Type: String
      Description: Customer Group PZ Endpoint
      Value: !Ref SeedCustomerGroupPZEndpoint
