AWSTemplateFormatVersion: 2010-09-09
Description: "Infrastructure of pricing service web service"
Parameters:
    environment:
        Description: Name of the environment
        Type: String
        Default: DEV
        AllowedValues:
            - DEV
            - STG
            - EXE
            - PROD
    namingPrefix:
        Description: Naming prefix for the components
        Type: String
        Default: cp-pricing
    ecrImageUri:
        Description: URI of the docker image used to run the api container
        Type: String
        Default: "037295147636.dkr.ecr.us-east-1.amazonaws.com/cp-pricing-service-dev:latest"
        AllowedValues:
            - "037295147636.dkr.ecr.us-east-1.amazonaws.com/cp-pricing-service-dev:latest"
            - "037295147636.dkr.ecr.us-east-1.amazonaws.com/cp-pricing-service-exe:latest"
            - "037295147636.dkr.ecr.us-east-1.amazonaws.com/cp-pricing-service-stg:latest"
            - "037295147636.dkr.ecr.us-east-1.amazonaws.com/cp-pricing-service-prod:latest"
    containerPort:
        Description: API container port number
        Type: Number
        Default: 8080
    albListenerPortHttp:
        Description: ALB HTTP Listener port number
        Type: Number
        Default: 80
    albListenerPortHttps:
        Description: ALB HTTPS Listener port number
        Type: Number
        Default: 443
    vpcId:
        Description: Name of VPC
        Type: String
        Default: "vpc-091c7e3e5578d7a4f"
    subnets:
        Description: Private Confidential Subnet
        Type: CommaDelimitedList
        Default: "subnet-0186b43162a344d9a,subnet-0ad1216eb31e15186,subnet-0a5d9eea71b9c97c6"
    taskRoleArn:
        Type: String
        Default: "arn:aws:iam::037295147636:role/cp-pricing-task-role"
    taskExecutionRoleArn:
        Type: String
        Default: "arn:aws:iam::037295147636:role/cp-pricing-execution-role"
    retentionPeriod:
        Description: Log retention period in days
        Type: Number
        Default: 365
        AllowedValues:
            - 90
            - 180
            - 365
            - 400
            - 731
            - 1827
            - 3653
    httpsListenerSslPolicy:
        Description: HTTPS listener SSL policy
        Type: String
        Default: ELBSecurityPolicy-2016-08
        AllowedValues:
            - ELBSecurityPolicy-2016-08
            - ELBSecurityPolicy-TLS-1-2-Ext-2018-06
    httpsListenerCertificateArn:
        Description: Certificate to use with the HTTPS listener
        Type: String
        Default: arn:aws:acm:us-east-1:037295147636:certificate/44f64fb1-43d9-4f60-b954-e4791e909321
Resources:
    ECSCluster:
        Type: AWS::ECS::Cluster
        Properties:
            ClusterName: !Join [ "-", [!Ref namingPrefix, ecs-cluster, !Ref environment]]
            ClusterSettings:
                - Name: containerInsights
                  Value: enabled
    TaskDefinition:
        Type: AWS::ECS::TaskDefinition
        Properties:
            Family: !Join [ "-", [!Ref namingPrefix, api-task-definition, !Ref environment]]
            Cpu: 2048
            Memory: 4096
            NetworkMode: awsvpc
            RequiresCompatibilities:
                - FARGATE
            TaskRoleArn: !Ref taskRoleArn
            ExecutionRoleArn: !Ref taskExecutionRoleArn
            ContainerDefinitions:
                - Name: !Join [ "-", [!Ref namingPrefix, api]]
                  Image: !Ref ecrImageUri
                  PortMappings:
                      - ContainerPort: !Ref containerPort
                        Protocol: tcp
                  Environment:
                      - Name: SERVER_ENVIRONMENT_VARIABLE
                        Value: !Ref 'environment'
                  LogConfiguration:
                      LogDriver: awslogs
                      Options:
                          awslogs-region: !Ref "AWS::Region"
                          awslogs-group: !Ref LogGroup
                          awslogs-stream-prefix: !Ref namingPrefix
    ECSService:
        Type: AWS::ECS::Service
        DependsOn:
            - ALBListenerHttp
            - ALBListenerHttps
        Properties:
            Cluster: !Ref ECSCluster
            ServiceName: !Join [ "-", [!Ref namingPrefix, ecs-service, !Ref environment]]
            TaskDefinition: !Ref TaskDefinition
            LaunchType: FARGATE
            HealthCheckGracePeriodSeconds: 60
            DesiredCount: 2
            DeploymentConfiguration:
                MaximumPercent: 100
                MinimumHealthyPercent: 50
            NetworkConfiguration:
                AwsvpcConfiguration:
                    AssignPublicIp: DISABLED
                    SecurityGroups:
                        - !Ref ECSServiceSecurityGroup
                    Subnets: !Ref subnets
            LoadBalancers:
                - ContainerName: !Join [ "-", [!Ref namingPrefix, api]]
                  ContainerPort: !Ref containerPort
                  TargetGroupArn: !Ref TargetGroup
    LogGroup:
        Type: AWS::Logs::LogGroup
        Properties:
            LogGroupName: !Join [ "-", [!Ref namingPrefix, log-group, !Ref environment]]
            RetentionInDays: !Ref retentionPeriod
    LoadBalancer:
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
            Name: !Join [ "-", [!Ref namingPrefix, alb, !Ref environment]]
            Scheme: internal
            Subnets: !Ref subnets
            SecurityGroups:
                - !Ref LoadBalancerSecurityGroup
    TargetGroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            Name: !Join [ "-", [!Ref namingPrefix, target-group, !Ref environment]]
            Port: !Ref containerPort
            Protocol: HTTP
            TargetType: ip
            VpcId: !Ref vpcId
            HealthCheckPath: '/pricing/support/healthcheck'
            HealthCheckIntervalSeconds: 30
            HealthCheckTimeoutSeconds: 5
            HealthyThresholdCount: 5
            UnhealthyThresholdCount: 3
    ALBListenerHttp:
        Type: AWS::ElasticLoadBalancingV2::Listener
        Properties:
            LoadBalancerArn: !Ref LoadBalancer
            Port: !Ref albListenerPortHttp
            Protocol: HTTP
            DefaultActions:
                - Type: forward
                  TargetGroupArn: !Ref TargetGroup
    ALBListenerHttps:
        Type: AWS::ElasticLoadBalancingV2::Listener
        Properties:
            LoadBalancerArn: !Ref LoadBalancer
            Port: !Ref albListenerPortHttps
            Protocol: HTTPS
            SslPolicy: !Ref httpsListenerSslPolicy
            Certificates:
                - CertificateArn: !Ref httpsListenerCertificateArn
            DefaultActions:
                - Type: forward
                  TargetGroupArn: !Ref TargetGroup
    ECSServiceSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupName: !Join [ "-", [!Ref namingPrefix, ecs-sg, !Ref environment]]
            GroupDescription: Pricing service ecs security group
            VpcId: !Ref vpcId
            SecurityGroupIngress:
                - CidrIp: "10.0.0.0/8"
                  IpProtocol: tcp
                  FromPort: !Ref containerPort
                  ToPort: !Ref containerPort
    LoadBalancerSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupName: !Join [ "-", [!Ref namingPrefix, alb-sg, !Ref environment]]
            GroupDescription: Pricing service load balancer security group
            VpcId: !Ref vpcId
            SecurityGroupIngress:
                - CidrIp: "10.0.0.0/8"
                  IpProtocol: tcp
                  FromPort: !Ref albListenerPortHttp
                  ToPort: !Ref albListenerPortHttp
                - CidrIp: "10.0.0.0/8"
                  IpProtocol: tcp
                  FromPort: !Ref albListenerPortHttps
                  ToPort: !Ref albListenerPortHttps
Outputs:
    LoadBalancerDNS:
        Description: Loadbalancer DNS
        Value: !GetAtt LoadBalancer.DNSName
