AWSTemplateFormatVersion: 2010-09-09
Description: This is the stack for CP Update Sync Job Definition
Parameters:
  EnvironmentShort:
    Description: Environment for application
    Type: String
    Default: PROD
    AllowedValues:
      - PROD
  EcrImage:
    Description: Environment for application
    Type: String
    Default: '130227353653.dkr.ecr.us-east-1.amazonaws.com/cp-update-sync:latest'
    AllowedValues:
      - '130227353653.dkr.ecr.us-east-1.amazonaws.com/cp-update-sync:latest'
  TaskRole:
    Description: ARN of task role attached to ECS task.
    Type: String
    Default: arn:aws:iam::130227353653:role/CloudPricing-Mimix-Purge-Job-Role

Resources:
  JobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      JobDefinitionName:
        Fn::Join:
          - ''
          - - CP-Update-Sync-Job-Definition-
            - Ref: 'EnvironmentShort'
      RetryStrategy:
        Attempts: 2
        EvaluateOnExit:
          - OnStatusReason: 'Timeout waiting for network interface provisioning to complete'
            Action: RETRY
          - OnStatusReason: 'ResourceInitializationError: unable to pull secrets or registry auth: pull command failed: : signal: killed'
            Action: RETRY
          - OnStatusReason: 'Job attempt duration exceeded timeout'
            OnExitCode: 143
            Action: RETRY
          - OnStatusReason: 'Essential container in task exited'
            OnExitCode: 1
            Action: RETRY
      Timeout:
        AttemptDurationSeconds: 10800
      PlatformCapabilities:
        - FARGATE
      ContainerProperties:
        Image: !Ref 'EcrImage'
        ResourceRequirements:
          - Type: VCPU
            Value: 4
          - Type: MEMORY
            Value: 8192
        ExecutionRoleArn: !Ref TaskRole
        Command:
          - java
          - "-Xmx6000M"
          - "-jar"
          - update-sync-processor.jar
          - Ref::business_unit
        JobRoleArn: !Ref 'TaskRole'
        Environment:
          - Name: 'SERVER_ENVIRONMENT_VARIABLE'
            Value: !Ref 'EnvironmentShort'
          - Name: 'TO_ADDRESSES'
            Value: 'sanjaya.amarasinghe@syscolabs.com,shetty.vidyasagar@corp.sysco.com,villanueva.loi@corp.sysco.com,amoda.dissanayake@sysco.com,chamin.wickramarathna@sysco.com,
                               gayan.herath@sysco.com,asanka.indunil@corp.sysco.com,gothami.karunarathna@syscolabs.com,piyumi.rameshka@sysco.com,
                               muqshid.mohamed@syscolabs.com,jayani.gajanayake@syscolabs.com,chandima.samarasinghe@syscolabs.com,chathurangi.edussuriya@syscolabs.com,
                               sahan.jayawardena@syscolabs.com,osanda.hemachandra@syscolabs.com,chandika.herath@syscolabs.com'

