AWSTemplateFormatVersion: 2010-09-09
Description: This is the stack for CP Update Sync Job Definition
Parameters:
  EnvironmentShort:
    Description: Environment for application
    Type: String
    Default: DEV
    AllowedValues:
      - DEV
      - EXE
      - STG
  TaskRole:
    Description: ARN of task role attached to ECS task.
    Type: String
    Default: arn:aws:iam::037295147636:role/CloudPricing-Mimix-Purge-Job-Role

Resources:
  JobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      JobDefinitionName:
        Fn::Join:
          - ''
          - - CP-Update-Sync-Job-Definition-
            - Ref: 'EnvironmentShort'
      RetryStrategy:
        Attempts: 1
      Timeout:
        AttemptDurationSeconds: 10800
      ContainerProperties:
        Image: '037295147636.dkr.ecr.us-east-1.amazonaws.com/cp-update-sync:latest'
        Vcpus: 4
        Memory: 8000
        Command:
          - java
          - "-Xmx6000M"
          - "-jar"
          - update-sync-processor.jar
          - Ref::business_unit
        JobRoleArn: !Ref 'TaskRole'
        Environment:
          - Name: 'SERVER_ENVIRONMENT_VARIABLE'
            Value: !Ref 'EnvironmentShort'
          - Name: 'TO_ADDRESSES'
            Value: 'chamin.wickramarathna@sysco.com,gayan.herath@sysco.com,asanka.indunil@corp.sysco.com,gothami.karunarathna@syscolabs.com,amoda.dissanayake@sysco.com'

