AWSTemplateFormatVersion: 2010-09-09
Description: This is the stack for CP Mimix Daily Purge Sync Job Definition
Parameters:
  Environment:
    Description: Environment for application
    Type: String
    Default: Development
    AllowedValues:
      - Development
      - Quality
      - Tuning
    ConstraintDescription: Must be a valid environment
  EnvironmentShort:
    Description: Environment for application
    Type: String
    Default: DEV
    AllowedValues:
      - DEV
      - QA
      - STG
  EmailSubject:
      Description: Subject for alert emails
      Type: String
      Default: MIMIX-Purging-Alerts-DEV
      AllowedValues:
        - MIMIX-Purging-Alerts-DEV
        - MIMIX-Purging-Alerts-QA
        - MIMIX-Purging-Alerts-STG
  TaskRole:
    Description: ARN of task role attached to ECS task.
    Type: String
    Default: arn:aws:iam::037295147636:role/CloudPricing-Mimix-Purge-Job-Role

Resources:
  JobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      JobDefinitionName:
        Fn::Join:
          - ''
          - - CP-Mimix-Purge-Job-Definition-
            - Ref: 'EnvironmentShort'
      RetryStrategy:
        Attempts: 1
      Timeout:
        AttemptDurationSeconds: 10800
      ContainerProperties:
        Image: '037295147636.dkr.ecr.us-east-1.amazonaws.com/cp-query-sync:latest'
        Vcpus: 4
        Memory: 6144
        Command:
          - java
          - "-Xmx6144M"
          - "-jar"
          - mimix-query-syncing-processor.jar
          - Ref::business_unit
        JobRoleArn: !Ref 'TaskRole'
        Environment:
          - Name: 'SERVER_ENVIRONMENT_VARIABLE'
            Value: !Ref 'EnvironmentShort'
          - Name: 'SENDER'
            Value: 'CloudPricingAlerts@corp.sysco.com'
          - Name: 'SUBJECT'
            Value: !Ref 'EmailSubject'
          - Name: 'TO_ADDRESSES'
            Value: 'amoda.dissanayake@sysco.com,chamin.wickramarathna@sysco.com,gayan.herath@sysco.com,asanka.indunil@corp.sysco.com,gothami.karunarathna@syscolabs.com'

