AWSTemplateFormatVersion: 2010-09-09
Description: This is the stack for CP Mimix Sync ECS cluster
Parameters:
    VPCID:
        Description: Name of the VPC for CP-NP
        Type: 'AWS::EC2::VPC::Id'
        Default: vpc-091c7e3e5578d7a4f
        ConstraintDescription: Must be a valid VPC.
    PemKey:
        Description: Name of and existing EC2 KeyPair to enable SSH access to the instance
        Type: 'AWS::EC2::KeyPair::KeyName'
        Default: KeyPair-Sysco-CloudPricing-NonProd
        MinLength: '1'
        MaxLength: '255'
        AllowedPattern: '[\x20-\x7E]*'
        ConstraintDescription: Must contain only ASCII characters.
    ImageId:
        Description: Amazon AMI
        Type: 'AWS::EC2::Image::Id'
        Default: 'ami-0c2b68244113d8b62'
    ApplicationName:
        Description: Name of application
        Type: String
        Default: 'Cloud Pricing'
        MinLength: '1'
        MaxLength: '255'
        AllowedPattern: '[\x20-\x7E]*'
        ConstraintDescription: Must contain only ASCII characters.
    ApplicationId:
        Description: Application ID
        Type: String
        Default: 'APP-001151'
        MinLength: '1'
        MaxLength: '255'
        AllowedPattern: '[\x20-\x7E]*'
        ConstraintDescription: Must contain only ASCII characters.
    PONumber:
        Description: PO Number for billing
        Type: String
        Default: '7000002358'
        MinLength: '1'
        MaxLength: '255'
        AllowedPattern: '[\x20-\x7E]*'
        ConstraintDescription: Must contain only ASCII characters.
    Approver:
        Description: Name of application approver
        Type: String
        Default: villanueva.loi@corp.sysco.com
        MinLength: '1'
        MaxLength: '255'
    Owner:
        Description: Name of application owner
        Type: String
        Default: villanueva.loi@corp.sysco.com
        MinLength: '1'
        MaxLength: '255'
    Environment:
        Description: Environment for application
        Type: String
        Default: EXE
        AllowedValues:
          - DEV
          - EXE
          - QA
          - STG
          - PROD
          - NONPROD
        ConstraintDescription: Must be a valid environment.
    ProjectId:
        Description: Project ID
        Type: String
        Default: 'BT.001176'
        MinLength: '1'
        MaxLength: '255'
        AllowedPattern: '[\x20-\x7E]*'
        ConstraintDescription: Must contain only ASCII characters.
    CPConfidentialSubnetA:
        Description: 'Private PRCP-NP Confidential Subnet 1 in us-east-1a CIDR: 10.133.103.0/24'
        Type: 'AWS::EC2::Subnet::Id'
        Default: subnet-0186b43162a344d9a
        MinLength: '1'
        MaxLength: '255'
        ConstraintDescription: Must be a valid Private Subnet.
    CPConfidentialSubnetB:
        Description: 'Private PRCP-NP Confidential Subnet 2 in us-east-1b CIDR: 10.133.105.0/24'
        Type: 'AWS::EC2::Subnet::Id'
        Default: subnet-0ad1216eb31e15186
        MinLength: '1'
        MaxLength: '255'
        ConstraintDescription: Must be a valid Private Subnet.
    CPConfidentialSubnetC:
        Description: 'Private PRCP-NP Confidential Subnet 3 in us-east-1c CIDR: 10.133.106.0/24'
        Type: 'AWS::EC2::Subnet::Id'
        Default: subnet-0a5d9eea71b9c97c6
        MinLength: '1'
        MaxLength: '255'
        ConstraintDescription: Must be a valid Private Subnet.
    SGWebServices: 
        Description: Security group for webServices
        Type: String
        Default: sg-0a56447308e39b902
    InstanceProfile:
        Description: Instance Profile Name
        Type: String
        Default: CloudPricing-IAM-InstanceProfile
    InstanceType:
        Description: Application EC2 instance type
        Type: String
        Default: c5.xlarge
    RootVolumeSize:
        Description: Size (GB) of root EBS volume for application instance
        Type: Number
        Default: '40'
        MinValue: '10'
        MaxValue: '1024'
    WorkloadNodesDesiredCapacity:
        Default: '1'
        Description: The desired capacity for the Workload nodes Auto Scaling group
        Type: String
    WorkloadNodesMaxSize:
        Default: '4'
        Description: The maximum size of the Auto Scaling group
        Type: String
    WorkloadNodesMinSize:
        Default: '1'
        Description: The minimum size of the Auto Scaling group
        Type: String

Resources:
    ECSCluster:
        Type: AWS::ECS::Cluster
        Properties:
            ClusterName: !Join
                - ''
                - - 'CP-Mimix-Sync-Ecs-Cluster-'
                  - !Ref 'Environment'

    ECSAutoScalingGroup:
        Type: AWS::AutoScaling::AutoScalingGroup
        UpdatePolicy:
            AutoScalingRollingUpdate:
              MaxBatchSize: '1'
              MinInstancesInService: '1'
              PauseTime: PT5M
              WaitOnResourceSignals: 'true'
        Properties:
            AutoScalingGroupName: !Join
                - ''
                - - 'cp-mimix-sync-auto-scaling-group-'
                  - !Ref 'Environment'
            AvailabilityZones:
                - us-east-1a
                - us-east-1b
                - us-east-1c
            VPCZoneIdentifier:
                - !Ref 'CPConfidentialSubnetA'
                - !Ref 'CPConfidentialSubnetB'
                - !Ref 'CPConfidentialSubnetC'
            LaunchConfigurationName: !Ref 'LaunchConfig'
            DesiredCapacity: !Ref 'WorkloadNodesDesiredCapacity'
            MaxSize: !Ref 'WorkloadNodesMaxSize'
            MinSize: !Ref 'WorkloadNodesMinSize'
            HealthCheckType: EC2
            Tags:
                - Key: Name
                  Value: !Join
                    - ''
                    - - 'cp-mimix-sync-auto-scaling-group-'
                      - !Ref 'Environment'
                  PropagateAtLaunch: 'true'
                - Key: Application_Name
                  Value: !Ref 'ApplicationName'
                  PropagateAtLaunch: 'true'
                - Key: Application_Id
                  Value: !Ref 'ApplicationId'
                  PropagateAtLaunch: 'true'
                - Key: Owner
                  Value: !Ref 'Owner'
                  PropagateAtLaunch: 'true'
                - Key: Approver
                  Value: !Ref 'Approver'
                  PropagateAtLaunch: 'true'
                - Key: PO_Number
                  Value: !Ref 'PONumber'
                  PropagateAtLaunch: 'true'
                - Key: Environment
                  Value: !Ref 'Environment'
                  PropagateAtLaunch: 'true'
                - Key: Project_ID
                  Value: !Ref 'ProjectId'
                  PropagateAtLaunch: 'true'
        DependsOn: ECSCluster
    
    LaunchConfig:
        Type: AWS::AutoScaling::LaunchConfiguration
        Properties:
            ImageId: !Ref 'ImageId'
            AssociatePublicIpAddress: false
            InstanceType: !Ref 'InstanceType'
            KeyName: !Ref 'PemKey'
            SecurityGroups:
                - !Ref 'SGWebServices'
            IamInstanceProfile: !Ref 'InstanceProfile'
            BlockDeviceMappings:
                - DeviceName: /dev/xvda
                  Ebs:
                      VolumeSize: !Ref 'RootVolumeSize'
                      VolumeType: gp2
            UserData: !Base64
                Fn::Join:
                    - ''
                    - - "#!/bin/bash\n"
                      - "sudo yum install -y ecs-init\n"
                      - "echo ECS_CLUSTER="
                      - !Ref 'ECSCluster'
                      - " >> /etc/ecs/ecs.config\n"
                      - "sudo service docker start\n"
                      - "sudo start ecs"
Outputs:
  ClusterARN:
    Description: The ECS Cluster ARN
    Value: !GetAtt ECSCluster.Arn