AWSTemplateFormatVersion: 2010-09-09
Description: This is the stack for CP Mimix Sync ECS task definition
Parameters:
  Environment:
    Description: Environment for application
    Type: String
    Default: EXE
    AllowedValues:
      - DEV
      - EXE
      - QA
      - STG
      - PROD
      - NONPROD
    ConstraintDescription: Must be a valid environment.
  ExecutionRole:
    Description: ARN of execution role attached to ECS task.
    Type: String
    Default: arn:aws:iam::037295147636:role/CloudPricing-Batch-IAM-Job-Role
  TaskRole:
    Description: ARN of task role attached to ECS task.
    Type: String
    Default: arn:aws:iam::037295147636:role/CloudPricing-Batch-IAM-Job-Role
  DockerImageArn:
    Description: Docker image of mimix sync processor
    Type: String
    Default: 037295147636.dkr.ecr.us-east-1.amazonaws.com/cp-mimix-sync
  CPUReserved:
    Description: The number of cpu units reserved for the container.
    Type: Number
    Default: '1024'
    MinValue: '256'
    MaxValue: '4096'
  MemoryReserved:
    Description: The soft limit (in MiB) of memory to reserve for the container.
    Type: Number
    Default: '2048'
    MinValue: '256'
    MaxValue: '8192'
  RetentionTime:
    Description: The number of days to retain the log events in the specified log group. Possible values are 1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, and 3653.
    Type: Number
    Default: '30'
    MinValue: '1'
    MaxValue: '3653'
Resources:
  LogGroup: 
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Join
        - ''
        - - '/aws/ecs/CP-Mimix-Sync-Task'
          - !Ref 'Environment'
      RetentionInDays: !Ref RetentionTime
  CpMimixSyncCustomerPricingTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: !Join
        - ''
        - - 'CP-MimixSync-Customer-Pricing-Task-Definition-'
          - !Ref 'Environment'
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: cp-mimix-sync-customer-pricing-container
          Essential: 'true'
          Image: !Ref DockerImageArn
          Cpu: !Ref CPUReserved
          MemoryReservation: !Ref MemoryReserved
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: ecs/CUSTOMER_PRICING
              awslogs-datetime-format: '%Y-%m-%d %H:%M:%S.%L'
          Environment:
            - Name: SERVER_ENVIRONMENT_VARIABLE
              Value: !Ref Environment
            - Name: SYNC_TYPE
              Value: CUSTOMER_PRICING
  CpMimixSyncFulfillmentTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: !Join
        - ''
        - - 'CP-MimixSync-Fulfillment-Task-Definition-'
          - !Ref 'Environment'
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: cp-mimix-sync-fulfillment-container
          Essential: 'true'
          Image: !Ref DockerImageArn
          Cpu: !Ref CPUReserved
          MemoryReservation: !Ref MemoryReserved
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: ecs/FULFILLMENT
              awslogs-datetime-format: '%Y-%m-%d %H:%M:%S.%L'
          Environment:
            - Name: SERVER_ENVIRONMENT_VARIABLE
              Value: !Ref Environment
            - Name: SYNC_TYPE
              Value: FULFILLMENT
  CpMimixSyncProductInfoTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: !Join
        - ''
        - - 'CP-MimixSync-ProductInfo-Task-Definition-'
          - !Ref 'Environment'
      ExecutionRoleArn: !Ref ExecutionRole
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: cp-mimix-sync-product-info-container
          Essential: 'true'
          Image: !Ref DockerImageArn
          Cpu: !Ref CPUReserved
          MemoryReservation: !Ref MemoryReserved
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: ecs/PRODUCT_INFO
              awslogs-datetime-format: '%Y-%m-%d %H:%M:%S.%L'
          Environment:
            - Name: SERVER_ENVIRONMENT_VARIABLE
              Value: !Ref Environment
            - Name: SYNC_TYPE
              Value: PRODUCT_INFO
Outputs:
  CustomerPricingTaskDefinition:
    Description: The Cp MimixSync CustomerPricing task definition ARN
    Value: !Ref CpMimixSyncCustomerPricingTaskDefinition
  FulfillmentTaskDefinition:
    Description: The Cp MimixSync CustomerPricing task definition ARN
    Value: !Ref CpMimixSyncFulfillmentTaskDefinition
  ProductInfoTaskDefinition:
    Description: The Cp MimixSync ProductInfo task definition ARN
    Value: !Ref CpMimixSyncProductInfoTaskDefinition