AWSTemplateFormatVersion: 2010-09-09
Description: "WTP Cleanup Script SSM Parameters"
Parameters:
  environment:
    Description: Name of the environment
    Type: String
    Default: DEV
    AllowedValues:
      - DEV
      - QE
      - EXE
      - STG
      - PROD
  paramStoreConfigPrefix:
    Type: String
    Default: "/CP/WTP_CLEANUP"
  paramStoreActiveBusinessUnits:
    Type: String
    Default: '018,024,035,039,047,057,059,061,064,066,194,195,332'
  paramLaunchDate:
    Type: String
    Default: '2021-06-12 00:00:00.0' 
  paramStoreDBHost:
    Type: String
    Default: 'cp-ref-price-db-cluster-01-dev.cluster-c6xai0tt38eb.us-east-1.rds.amazonaws.com'
Resources:
  ConfigActiveBusinessUnits:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["/", [!Ref paramStoreConfigPrefix, !Ref environment, ACTIVE/BUSINESS/UNITS]]
      Type: String
      Description: Active business units
      Value: !Ref paramStoreActiveBusinessUnits
  ConfigLaunchDate:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["/", [!Ref paramStoreConfigPrefix, !Ref environment, LAUNCH/DATE]]
      Type: String
      Description: Periscope launch date for the sites
      Value: !Ref paramLaunchDate
  ConfigDBHost:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["/", [!Ref paramStoreConfigPrefix, !Ref environment, PRICING/DB/HOST]]
      Type: String
      Description: DB host
      Value: !Ref paramStoreDBHost